name: Check Issues

on:
  pull_request:
    branches:
      - development
      - hotfix
      - main
    types:
      - edited
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_call:

jobs:
  check-issues:
    name: Check Issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: '10.15.0'
      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          cache: 'pnpm'
          node-version: '22.18.0'
      - name: Install dependencies
        run: pnpm install
      - name: Check linter errors
        run: pnpm run lint
      - name: Test library
        run: pnpm run test
      - name: Build library
        run: pnpm run build
      - name: Upload backend build files
        uses: actions/upload-artifact@v4
        with:
          name: jscv-solutions-logger
          if-no-files-found: 'error'
          path: dist
      #- name: List artifacts for this run (debug)
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  run: |
      #    echo "Run ID: $GITHUB_RUN_ID"
      #    curl -sSL \
      #      -H "Authorization: Bearer $GITHUB_TOKEN" \
      #      -H "Accept: application/vnd.github+json" \
      #      "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/artifacts" \
      #      | jq .
